### ISSUE TITLE
Option to wait for device ready event on "@Cordova"-decorator

### ISSUE THREAD

**Issue by DomiR** [danielsogl/awesome-cordova-plugins#100]
Shouldn't all plugin-calls wait for the device-ready-promise to be fulfilled?

Or could we at least have an option to delay plugin-calls until the device is ready?

``` ts
import {Plugin, Cordova} from 'ionic-native';
...
export class Test{
    @Cordova(onDeviceReady:true)
    static startTrackerWithId(id:string): Promise<any> { return }
}
```

**Comment by ihadeed** [comment]
Good idea.

For some reason I thought Ionic Native already does that...

It might be a good idea to wait for the `onDeviceReady` event by default since many plugins rely on it.

**Comment by Ritzlgrmft** [comment]
:+1:

**Comment by ihadeed** [comment]
Just pushed a new branch that addresses this feature request. 

https://github.com/driftyco/ionic-native/compare/feat/ondeviceready?expand=1

The way it works is that if we are calling an async function (the ones that return Promise or Observable), we will wait for ondeviceready to fire before we go ahead and make the call.

I haven't tested it but in theory it should work. 

If the developer is trying to access a sync function or a property, they will have to wrap it with an event listener manually in order to get it to work.

CC: @mlynch @tlancina @mhartington

**Comment by mlynch** [comment]
@ihadeed it's a good idea. Will that event fire multiple times even if it already happened? I'm getting conflicting info online, the docs say that the callback will happen immediately after the first time but not sure about that. If not, we'd want a global handler and a global ready flag, which might be more performant anyways than binding a listener on each call

**Comment by ihadeed** [comment]
@mlynch 

I just read this in the Cordova Docs: https://cordova.apache.org/docs/en/latest/cordova/events/events.html#deviceready

> The deviceready event behaves somewhat differently from others. Any event handler registered after the deviceready event fires has its callback function called immediately.

**Comment by ihadeed** [comment]
@mlynch I'll leave it up to you to add this feature (merge PR) or leave it out.
