### ISSUE TITLE
Output all ionic-native plugins and if their needed plugins are installed/available

### ISSUE THREAD

**Issue by janpio** [danielsogl/awesome-cordova-plugins#1814]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

**Description:**

It would be great if `@ionic-native/core` provided some functionality that listed all installed ionic-native plugins and their underlying Cordova plugins and if they are installed and available. This would probably best be implemented as a simple function that gives an object as return value that can be `console.log`ged.

**Comment by ihadeed** [comment]
@janpio 

I wrote some code awhile ago to have Ionic Native automatically install the required plugins when you install the `@ionic-native/*` NPM package. That's why [some plugins](https://github.com/ionic-team/ionic-native/search?utf8=%E2%9C%93&q=installVariables&type=) have `installVariables` defined in the config.

![image](https://user-images.githubusercontent.com/13794420/28488126-5566577e-6e71-11e7-8b4d-efef8d7796f3.png)

It needs some improvements though. It runs through npm scripts, and that comes with some issues. I thought it would be better to have an Ionic CLI tool that takes care of this stuff. Something like:
```shell
# this will run the following two commands:
# - npm i --save @ionic-native/file
# - ionic cordova plugin add cordova-plugin-file
ionic native add file

# update all ionic native packages
ionic native update

# update ionic native packages + cordova plugins
ionic native update -a 

# update one plugin
ionic native update file

# update one plugin and it's cordova plugin
ionic native update file -a
```

**Comment by janpio** [comment]
That sounds like a great idea.

My suggestion was more a runtime debugging thing, an easy way to help people debug things when they don't work. Cordova plugins are just so unreliable (especially those with parameters - or broken package names).
