### ISSUE TITLE
Geofence wrapper doesn't catch plugin error

### ISSUE THREAD

**Issue by josh-m-sharpe** [danielsogl/awesome-cordova-plugins#1920]
Bug Report:

geofence plugin: 0.7.0
ionic-native: 3.12.1

Using geofence the "ionic native" ([link to docs](http://ionicframework.com/docs/native/geofence/)) way results in an unhandled exception bubbling up when location perms have not been granted (or, presumably, when any other plugin exception occurs).

```
this.geofence.initialize().then(
  // resolved promise does not return a value
  () => console.log('Geofence Plugin Ready'),
  (err) => console.log(err)
)
```

results in:

```
Unhandled Promise rejection: (8)
"Warning: Location always permissions not granted
Error: notification permission missing"
```

However, if the plugin is used directly, the error is correctly caught, and in this case, logged:

```
window['geofence'].initialize().then(
  // resolved promise does not return a value
  () => console.log('Geofence Plugin Ready'),
  (err) => console.log(err)
)
```

It's a bit hard to illustrate here.  Using the first block of code there, exceptions show up as Errors (red) in safari's console.  Using the second block, they show up like any other log statement.

**Comment by lunedam-git** [comment]
I see this too. Have ended up using the "window['geofence'].method..." way and the plugin docs rather than the ionic-native wrapper.

Also. I also find that I need something 'else' (such as the geolocation plugin, or native map app) watching the current location before the geofence plugin reacts to a fence boundary being crossed. Docs don't mention this requirement. Is it just me?
