### ISSUE TITLE
UserAgent plugin_not_installed

### ISSUE THREAD

**Issue by smxdevst** [danielsogl/awesome-cordova-plugins#2287]
**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request

```
[17:33:56]  console.warn: Native: tried calling UserAgent.set, but the UserAgent plugin is not installed. 
[17:33:56]  console.warn: Install the UserAgent plugin: 'ionic cordova plugin add cordova-plugin-useragent' 
[17:33:56]  console.error: plugin_not_installed 
```

Installed `ionic cordova plugin add cordova-plugin-useragent`. I am running userAgent.set after platform ready, tried to reinstall everything and install it back. Any suggestions?

package.json
`"im.ltdev.cordova.UserAgent": "https://github.com/LouisT/cordova-useragent"`

config.xml
`<plugin name="im.ltdev.cordova.UserAgent" spec="https://github.com/LouisT/cordova-useragent" />`

**Comment by amyogiji** [comment]
Had Similar problem with ionic cordova plugin add cordova-plugin-file
So i installed the older version ionic cordova plugin add cordova-plugin-file@4.3.3
Now it works.

**Comment by smxdevst** [comment]
@amyogiji  There is only 1 version of it. No releases on this plugin

**Comment by codewise-nicolas** [comment]
I dont know how long I spent on this problem, but i finally figured it out.
The pluginRef in the ionic-native is set wrong.

The cordova plugin has the "clobbers target" set to "UserAgent", however the ionic-native plugin's node_modules/@ionic-native/user-agent/index.js has the pluginRef set to "plugins.useragent". They should match.

Not sure where the difference/discrepancy happened but it did, and the fix is to change the node_modules/@ionic-native/user-agent/index.js of the ionic-native user-agent plugin's pluginRef to "UserAgent". (dont forget to remove, re-add the ios/android platform for the change to get picked up)
Alternatively change the plugin's clobbers target to plugins.useragent, i found the former easier.

I dont have the time/knowledge to submit a patch to Ionic's repo, but thats the fix you can do locally.

**Comment by TimeTravelersHackedMe** [comment]
still an issue...

**Comment by nscozzaro** [comment]
I'm facing a similar issue. 
![image](https://user-images.githubusercontent.com/15185105/52918424-cca73600-32c4-11e9-886d-9b3034d258d5.png)

I tried following the instructions from @codewise-nicolas but the pluginref was already set to useragent:
![image](https://user-images.githubusercontent.com/15185105/52918432-eb0d3180-32c4-11e9-8eda-7058de415da6.png)

**Comment by nscozzaro** [comment]
I'm facing a similar issue: 
```Discovered plugin "im.ltdev.cordova.UserAgent" in config.xml. Adding it to the project
Failed to restore plugin "im.ltdev.cordova.UserAgent" from config.xml. ```
![image](https://user-images.githubusercontent.com/15185105/52918490-91593700-32c5-11e9-9cbe-110ee55d689e.png)


I tried following the instructions from @codewise-nicolas but the pluginref was already set to useragent:
![image](https://user-images.githubusercontent.com/15185105/52918495-a03fe980-32c5-11e9-8730-a31fc99db6ad.png)

**Comment by codewise-nicolas** [comment]
From the screenshot it looks like somewhere in your files it is still
referring to the wrong plugin.

Notice its trying to grab im.ltdev...
