### ISSUE TITLE
cordova-plugin-request-location-accuracy stops working on iOS after 2 invocations

### ISSUE THREAD

**Issue by nalkon** [danielsogl/awesome-cordova-plugins#2557]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Expected behavior:**
When location services are off on a device, the plugin is supposed to invoke system settings so user can turn on location services manually

**Current behavior:**
System settings are being invoked only 2 times after an app is installed on a device. After 2 times, system settings won't open. Ever. You need to re-install the app to make it work again.

**Steps to reproduce:**
1. Install an app that uses cordova-plugin-request-location-accuracy
2. Turn off location services
3. Start the app. 
4. Plugin is supposed to invoke system settings. Turn on location services.
5. Repeat steps 2 - 4 twice. On the third time of running this scenario, system settings won't open.

**Related code:**

```
this.locationAccuracy.canRequest().then((canRequest: boolean) => {
      if(canRequest) {
        this.locationAccuracy.request(this.locationAccuracy.REQUEST_PRIORITY_HIGH_ACCURACY).then(() => {
          console.log("Request location accuracy success");
        },
          error => {
            console.log('Error requesting location permissions', error);
          }
        );
      }
    });
```

**Other information:**
The problem happens on any iPhone model and any iOS version
cordova-plugin-request-location-accuracy: v 2.2.3

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.1.10
    Cordova Platforms  : android 6.2.3 ios 4.5.2
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2 
    Node       : v9.5.0
    npm        : 5.6.0 
    OS         : macOS Sierra
    Xcode      : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : legacy

```

**Comment by dpa99c** [comment]
This is the behaviour that Apple intends for iOS, in order to prevent users harassed by apps to allow a particular permission: if the user turns off location services twice and the app requests to turn it back on twice, iOS assumes the user meant to keep location services turned off and therefore prevents the app from showing the system settings dialog again. This is similar to the [iOS Cancel button caveat](https://github.com/dpa99c/cordova-plugin-request-location-accuracy#ios-cancel-button-caveat).

Therefore, there's nothing that the plugin (or any native iOS code) can do to override this.

I would also point out that, though the outlined steps to reproduce this are possible, a real user is very unlikely to follow them: i.e. intentionally manually disable Location Services twice then re-enable via the Settings dialog.

**Comment by indraraj26** [comment]
in my case, that popup comes only for first time if the user cancel that popup next time i always get true and success. With that i am not able to detect whether user is enabled the location service or not.
if the mobile location service is disabled then isLocationEnabled and isLocationAvaiable from diagnostic will always return N/A.
