### ISSUE TITLE
Firebase getValue() does not resolve.

### ISSUE THREAD

**Issue by Sebschock** [danielsogl/awesome-cordova-plugins#2603]
**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
The function getValue does not return anything on iOS. Nothing is logged by:
```
this.firebase.getValue('test_val').then((result) => {
  console.log(result);
}).catch((error) => {
  console.log(error);
});
```
If I use the plugin directly, the result is logged: 
```
(<any>window).FirebasePlugin.getValue('test_val', result => {
  console.log(result);
});
```

The `fetch()` and `activateFetched()` functions works as expected in same script.

**Expected behavior:**
For the getValue promise to be resolve/rejected on iOS

**Comment by andrey3diq** [comment]
The same thing for me on android.

**Comment by askona** [comment]
This is not working because of { "successIndex": 1, "errorIndex": 2 }
Firebase.**fetch** not working too.
@danielsogl Please fix this. Seems it's not a very hard to fix.
`
    Firebase.prototype.fetch = function (cacheExpirationSeconds) { return cordova(this, "fetch", { "successIndex": 1, "errorIndex": 2 }, arguments); };
`
`Firebase.prototype.getValue = function (key, namespace) { return cordova(this, "getValue", { "successIndex": 2, "errorIndex": 3 }, arguments); };
`
