### ISSUE TITLE
@ionic-native/...   and RXJS ^7.5.6

### ISSUE THREAD

**Issue by pelord** [danielsogl/awesome-cordova-plugins#4332]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use the discussions section https://github.com/danielsogl/awesome-cordova-plugins/discussions

**Current behavior:**
I use theses version

    "@ionic-native/core": "^5.10.0",
    "@ionic-native/file": "^5.6.0",
    "@ionic-native/file-opener": "^5.6.0",
    "@ionic-native/network": "^5.12.0",

with 

    "rxjs": "^7.5.6",

Here what I get on npm install

![image](https://user-images.githubusercontent.com/7397743/191998149-e8e174ed-dde1-4adf-a5bb-6da2f1009566.png)

**Expected behavior:**
Is it in your plan to support rxjs 7.5.x soon?

**Comment by pelord** [comment]
https://github.com/danielsogl/awesome-cordova-plugins/pull/3925

**Comment by QuentinLeGoff** [comment]
Any news ?

**Comment by danielsogl** [comment]
This library already supports the latest rxjs release as you can see here: https://github.com/danielsogl/awesome-cordova-plugins/blob/0922b468a2d164047da4c226a3ec8477de641cdf/scripts/tasks/publish.ts#L34

Because you are still using the old `@ionic-native/*` packages you have to update them to `@awesome-cordova-plugins/*`

**Comment by pelord** [comment]
Does the @ionic-native/* is deprecated? Awesome-cordova-plugins is the new repo to use in remplacement?
