### ISSUE TITLE
missing getBluetoothAuthorizationStatuses from Diagnostic

### ISSUE THREAD

**Issue by si458** [danielsogl/awesome-cordova-plugins#4432]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, use the discussions section https://github.com/danielsogl/awesome-cordova-plugins/discussions

**Current behavior:**

`getBluetoothAuthorizationStatuses` is missing from the diagnostics module

**Expected behavior:**

`getBluetoothAuthorizationStatuses` to exist

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by infacto** [comment]
https://github.com/dpa99c/cordova-diagnostic-plugin#getbluetoothauthorizationstatuses

**Comment by infacto** [comment]
I made a pull request. Btw. we should avoid `any` types. I know this is not always that easy. Since the source code or docs are also a bit cryptic. In this case it returns an object with permission name as key and the permission state as value. In typescript `Record<string, string>` or better with enum or specific type instead of just string. But we must be 100% sure when restricting with types. Anyway, it's another issue. It would be great if someone could review and merge the pull reqeust and file a new release.
