### ISSUE TITLE
Invalid package.json field for sub packages

### ISSUE THREAD

**Issue by BreakBB** [danielsogl/awesome-cordova-plugins#4536]
## Description

The `package.json` in released sub packages such as [is-debug](https://github.com/danielsogl/awesome-cordova-plugins/tree/master/src/%40awesome-cordova-plugins/plugins/is-debug) reference a "bundle.js" in their `main` field which is only valid for the [core module](https://github.com/danielsogl/awesome-cordova-plugins/tree/master/src/%40awesome-cordova-plugins/core).

https://github.com/danielsogl/awesome-cordova-plugins/blob/d7c771b2505c47e79bdab775d55b7ba3da8dcd8e/scripts/tasks/publish.ts#L18

That results in an issue for newly created vite projects:

```js
import {IsDebug} from '@awesome-cordova-plugins/is-debug';
```

> Error: Failed to resolve entry for package "@awesome-cordova-plugins/is-debug". The package may have incorrect main/module/exports specified in its package.json.

## Proposal

The [publish.ts](https://github.com/danielsogl/awesome-cordova-plugins/blob/master/scripts/tasks/publish.ts) should become aware of the modules it is building the `package.json` for and drop the `main` field for everything except the core module.

**Comment by Tallyb** [comment]
This is critical! it makes the packages unusable with variety of tools

**Comment by daohoangson** [comment]
Apparently this was introduced 2 years ago via #3483:
- `generateLegacyBundles` was added to rollup CJS from `core/index.js` and `plugins/**/ngx/index.js`.
- The core index file is in root so its `bundle.js` is put there
- The plugin's one is in `ngx` directory so the generated file is in the subdirectory
- The `main` field in `PACKAGE_JSON_BASE` doesn't take this into account so it's always reference the root file and triggers warning in different tools.

There are 2 approaches to fix for this IMHO:

1. Update `generateLegacyBundles` to target plugin root index.js file instead of the Angular one.
2. Or adjust `main` field for plugins

I think the first approach is more correct. Paging @laurentgoudet, what do you think?

**Comment by coltanium13** [comment]
We have noticed this same issue in our vite project, with the ```web-intent``` sub package as well. If you remove the ```main``` property from the web-intent's package.json file, it seems to work ok. Can we get a fix to these sub packages? Thank you!

**Comment by BreakBB** [comment]
Any news on this @danielsogl ?

**Comment by BreakBB** [comment]
The repo doesn't seem to be abandoned, still there is no reply from a maintainer?
